name = "SimpleDualAscent"
uuid = "13b6d80f-aca1-4b82-90b1-7f9b03820ae7"
authors = ["Klamkin, Michael <michael@klamkin.com>"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
